FROM node:20-alpine AS build
WORKDIR /app

ARG VITE_MODULE_API_URL=http://178.57.217.79:8080
ARG VITE_MODULE_PLANNING_URL=http://178.57.217.79:5173
ARG VITE_MODULE_ECO_URL=http://178.57.217.79:8001
ENV VITE_MODULE_API_URL=$VITE_MODULE_API_URL
ENV VITE_MODULE_PLANNING_URL=$VITE_MODULE_PLANNING_URL
ENV VITE_MODULE_ECO_URL=$VITE_MODULE_ECO_URL

COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.docker.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
