# Generated by Django 5.2.14 on 2026-05-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('indicator_type', models.CharField(choices=[('air', 'воздух'), ('wastewater', 'сточные воды'), ('soil', 'почва'), ('noise', 'шум')], max_length=20, verbose_name='тип показателя')),
                ('value', models.DecimalField(decimal_places=4, help_text='фактическое значение измерения', max_digits=12, verbose_name='значение')),
                ('norm', models.DecimalField(decimal_places=4, help_text='предельно допустимое или нормативное значение', max_digits=12, verbose_name='норматив')),
                ('measurement_date', models.DateField(verbose_name='дата измерения')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='organizations.organization', verbose_name='организация')),
            ],
            options={
                'verbose_name': 'измерение',
                'verbose_name_plural': 'измерения',
                'ordering': ['-measurement_date', '-created_at'],
            },
        ),
    ]
