# Generated by Django 5.2.14 on 2026-05-12 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='название отхода')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='код отхода')),
                ('hazard_class', models.PositiveSmallIntegerField(help_text='от 1 до 5 по классификации опасности отходов', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='класс опасности')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'вид отхода',
                'verbose_name_plural': 'виды отходов',
                'ordering': ['code', 'name'],
            },
        ),
    ]
