"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-6_au2kf=eqbi+6dzy75j4u1(6!_$!yr(-+mo0vpp$-fpe@)22v",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Учебный проект: порядок важен — сначала справочники, потом журналы
    'apps.organizations',
    'apps.administration',
    'apps.waste',
    'apps.operations',
    'apps.monitoring',
    'apps.dashboard',
    'apps.integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.integrations.middleware.ApiTokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Общие шаблоны проекта (например registration/login.html)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.integrations.context_processors.api_integration',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Локальная SQLite НЕ хранит отходы/операции/измерения для интерфейса.
# Все учётные данные общего проекта — PostgreSQL на сервере API (модули одногруппников).
# Здесь только: сессия Django, JWT в session, служебная копия User после входа через API.
_sqlite_path = os.environ.get("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _sqlite_path,
    }
}

# Внешняя платформа «Учёт и переработка промышленных отходов»
USE_REMOTE_API = os.environ.get('USE_REMOTE_API', 'true').lower() in ('1', 'true', 'yes')
# Логин и пароль проверяются на сервере API (POST /api/v1/auth/login)
USE_API_AUTH = os.environ.get('USE_API_AUTH', 'true').lower() in ('1', 'true', 'yes')
API_BASE_URL = os.environ.get('API_BASE_URL', 'http://178.57.217.79:8080').rstrip('/')
# (подключение, чтение) в секундах — сервер 178.57.217.79 иногда отвечает медленно
API_TIMEOUT = float(os.environ.get('API_TIMEOUT', '30'))
API_CONNECT_TIMEOUT = float(os.environ.get('API_CONNECT_TIMEOUT', '10'))


def _sibling_module_url(env_name: str, default_port: int) -> str:
    """URL соседнего UI-модуля; хост берётся из API_BASE_URL, если не задан явно."""
    explicit = os.environ.get(env_name, '').strip()
    if explicit:
        return explicit.rstrip('/')
    from urllib.parse import urlparse

    parsed = urlparse(API_BASE_URL)
    host = parsed.hostname or 'localhost'
    scheme = parsed.scheme or 'http'
    return f'{scheme}://{host}:{default_port}'


MODULE_API_URL = _sibling_module_url('MODULE_API_URL', 8080)
MODULE_PLANNING_URL = _sibling_module_url('MODULE_PLANNING_URL', 5173)
MODULE_ECO_URL = _sibling_module_url('MODULE_ECO_URL', 8001)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Вход и редирект после успешного входа на дашборд
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Сообщения: уровень ERROR отображаем как Bootstrap alert-danger
from django.contrib.messages import constants as message_constants

CSRF_TRUSTED_ORIGINS = [
    'http://runcourse.online',
    'https://runcourse.online',
    'http://www.runcourse.online',
    'https://www.runcourse.online',
    'http://eco.runcourse.online',
    'https://eco.runcourse.online',
    'http://plan.runcourse.online',
    'https://plan.runcourse.online',
    'http://178.57.217.79:8001',
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MESSAGE_TAGS = {
    message_constants.DEBUG: "secondary",
    message_constants.INFO: "info",
    message_constants.SUCCESS: "success",
    message_constants.WARNING: "warning",
    message_constants.ERROR: "danger",
}
