# Generated by Django 5.2.14 on 2026-05-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('operation_type', models.CharField(choices=[('accumulation', 'накопление'), ('recycling', 'переработка'), ('removal', 'вывоз')], max_length=20, verbose_name='тип операции')),
                ('volume', models.DecimalField(decimal_places=3, help_text='масса или объём в тоннах (учебный пример)', max_digits=12, verbose_name='объём, т')),
                ('operation_date', models.DateField(verbose_name='дата операции')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='organizations.organization', verbose_name='организация')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='waste.wastetype', verbose_name='тип отхода')),
            ],
            options={
                'verbose_name': 'движение отходов',
                'verbose_name_plural': 'движения отходов',
                'ordering': ['-operation_date', '-created_at'],
            },
        ),
    ]
